"""
Django settings for click_and_collect_project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# BASE_DIR définit le chemin absolu vers le dossier racine du projet (là où se trouve manage.py).
# Il sert de référence pour trouver la base de données, les dossiers de templates ou de médias.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: clé secrète utilisée par Django pour signer de manière cryptographique 
# les sessions et les cookies. En production, elle doit rester absolument secrète !
SECRET_KEY = 'django-insecure-0ked8e$^yd!qb6_*cmw_h9e1$n3lo^9+)z*2a7mpkf$h@dd&$l'

# SECURITY WARNING: DEBUG = True affiche des traces d'erreurs détaillées en cas de bug.
# À passer OBLIGATOIREMENT à False en production pour ne pas fuiter le code ou la structure de la BDD.
DEBUG = True

# Liste des noms de domaines sur lesquels l'application a le droit d'être hébergée (ex: 'monsite.fr')
ALLOWED_HOSTS = []


# --- Définition de l'Application ---

# Liste de toutes les applications actives dans le projet.
# Django vient avec des "apps" de base (admin, auth, sessions), auxquelles on ajoute les nôtres.
INSTALLED_APPS = [
    'django.contrib.admin',       # Interface d'administration
    'django.contrib.auth',        # Système d'authentification (User, Login, etc.)
    'django.contrib.contenttypes',# Framework de types de contenus
    'django.contrib.sessions',    # Gestion des sessions utilisateurs (pour le panier)
    'django.contrib.messages',    # Messages flash (succès, erreur temporaire)
    'django.contrib.staticfiles', # Gestion des fichiers statiques (CSS, JS)
    
    # --- Nos applications ---
    'boutique', # L'application principale du projet Click & Collect
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# --- Base de données ---
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Configuration de la BDD. Par défaut, Django utilise SQLite3,
# un moteur stockant toutes les données dans un simple fichier à la racine (db.sqlite3).
# En production, on utiliserait plutôt PostgreSQL ou MySQL.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# --- Fichiers Statiques et Médias ---
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATIC_URL : L'URL de base pour charger les fichiers CSS/JS publics dans le navigateur.
STATIC_URL = 'static/'

# MEDIA_URL : L'URL de base pour accéder aux fichiers uploadés (ex: /media/produits/image.jpg)
MEDIA_URL = '/media/'
# MEDIA_ROOT : Le chemin absolu sur le disque dur vers le dossier où sont stockés physiquement les uploads
MEDIA_ROOT = BASE_DIR / 'media'

# LOGIN_REDIRECT_URL : Redirection automatique de l'utilisateur une fois connecté avec succès
LOGIN_REDIRECT_URL = '/boutique/' 
# LOGOUT_REDIRECT_URL : Redirection automatique de l'utilisateur après s'être déconnecté
LOGOUT_REDIRECT_URL = '/boutique/'